version: '3.3'
services:
  lrzdct:
    build:
      context: ..
      dockerfile:    lrzdct/Dockerfile
      args:
        OS:  "debian"
        VER: "latest"
    restart: always
    #hostname:        lrzdct
    image: innovanon/lrzdct:latest
    #container_name:  lrzdct
    ports:
      - "27601:27601"
      - "27602:27602"
    networks:
#      innovanon:
#        aliases:
#          - lrzdct.innovanon.com
      lrzdct:
        aliases:
          - lrzdct.innovanon.com

networks:
  lrzdct:
#  innovanon:
#    external: true

