version: '3.3'
services:
  cksum:
    build:
      context: ..
      dockerfile:    cksum/Dockerfile
      args:
        OS:  "debian"
        VER: "latest"
    restart: always
    #hostname:        cksum
    image: innovanon/cksum:latest
    #container_name:  cksum
    ports:
      - "27500:27500"
      - "27501:27501"
      - "27502:27502"
      - "27503:27503"
      - "27504:27504"
      - "27505:27505"
      - "27506:27506"
    networks:
#      innovanon:
#        aliases:
#          - cksum.innovanon.com
      cksum:
        aliases:
          - cksum.innovanon.com

networks:
#  innovanon:
#    external: true
  cksum:

