version: '3.3'
services:
  lrzpoo:
    build:
      context: ..
      dockerfile:    lrzpoo/Dockerfile
      args:
        OS:  "ubuntu"
        VER: "latest"
    restart: always
    #hostname:        lrzpoo
    image: innovanon/lrzpoo:latest
    #container_name:  lrzpoo
    ports:
      - "27617:27617"
      - "27618:27618"
      - "27623:27623"
      - "27624:27624"
    networks:
#      innovanon:
#        aliases:
#          - lrzpoo.innovanon.com
      lrzpoo:
        aliases:
          - lrzpoo.innovanon.com

networks:
  lrzpoo:
#  innovanon:
#    external: true

