version: '3.3'
services:
  tlrz:
    build:
      context: ..
      dockerfile:    tlrz/Dockerfile
      args:
        OS:  "debian"
        VER: "latest"
    restart: always
    #hostname:        tlrz
    image: innovanon/tlrz:latest
    #container_name:  tlrz
    ports:
      # tlrz
      - "27600:27600"
      - "27601:27601"
      # xz
      - "27604:27604"
      - "27605:27605"
      # bzip2
      - "27606:27606"
      - "27607:27607"
      # gzip
      - "27608:27608"
      - "27609:27609"
      # compress
      # lzma
      - "27610:27610"
      - "27611:27611"
      # lzip
      - "27612:27612"
      - "27613:27613"
      # lzop
      - "27614:27614"
      - "27615:27615"
      # rar
      - "27618:27618"
      - "27619:27619"
      # zip
      - "27620:27620"
      - "27621:27621"
    networks:
#      innovanon:
#        aliases:
#          - tlrz.innovanon.com
      tlrz:
        aliases:
          - tlrz.innovanon.com

networks:
  tlrz:
#  innovanon:
#    external: true

